### ISSUE TITLE
关于 CUDA 版本

### ISSUE THREAD

**Issue by USTBcvpaperreading** [EasyRy/RepKPU#1]
作者您好。在配置文件您写的是CUDA12.2，但是貌似和 torch 版本匹配不上，以及你用的是 python3.6，所以我猜测是否这里你用的是 CUDA10.2，而不是 CUDA12.2。

**Comment by USTBcvpaperreading** [comment]
追问：其他版本的 CUDA 和 Torch 是否可以运行这个工程呢？我用的是 python3.8，pytorch2.2，cuda11.8，在cd ../pointops
python setup.py install这一步出现编译错误。

**Comment by EasyRy** [comment]
您好！
1. 我这个虚拟环境一开始确实是在CUDA10.2上的，但后来升级成12.2了，虚拟环境还是可以照常使用。所以我写了12.2
2. 只要是能正常运行upsampling(例如Grad-PU)，completion(例如SeedFormer & SnowflakeNet)模型的环境都能正常运行这个工程(ps. 我的另一completion的repo和这个共享同一个环境）。你可以去这些repo下面找找类似的issue。
